with source as (

    select * from {{ source('sources', 'web_sales') }}

limit 10)
,

transformed as (

select 



 WS_SHIP_CUSTOMER_SK as customer_key_sk -- NUMBER
, WS_LIST_PRICE as list_price -- NUMBER
, WS_WEB_SITE_SK as website_sk -- NUMBER
, WS_QUANTITY as quantity -- NUMBER
, WS_NET_PAID as net_paid -- NUMBER
, WS_NET_PROFIT as net_profit -- NUMBER
, WS_SALES_PRICE as sales_price -- NUMBER
, WS_WHOLESALE_COST as cost -- NUMBER

, WS_SHIP_ADDR_SK as WS_SHIP_ADDR_SK -- NUMBER
, WS_ITEM_SK as WS_ITEM_SK -- NUMBER
, WS_SHIP_CDEMO_SK as WS_SHIP_CDEMO_SK -- NUMBER
, WS_EXT_TAX as WS_EXT_TAX -- NUMBER
, WS_EXT_DISCOUNT_AMT as WS_EXT_DISCOUNT_AMT -- NUMBER
, WS_EXT_SHIP_COST as WS_EXT_SHIP_COST -- NUMBER
, WS_BILL_ADDR_SK as WS_BILL_ADDR_SK -- NUMBER
, WS_BILL_CDEMO_SK as WS_BILL_CDEMO_SK -- NUMBER
, WS_SHIP_MODE_SK as WS_SHIP_MODE_SK -- NUMBER
, WS_NET_PAID_INC_SHIP_TAX as WS_NET_PAID_INC_SHIP_TAX -- NUMBER
, WS_COUPON_AMT as WS_COUPON_AMT -- NUMBER
, WS_EXT_WHOLESALE_COST as WS_EXT_WHOLESALE_COST -- NUMBER
, WS_EXT_LIST_PRICE as WS_EXT_LIST_PRICE -- NUMBER
, WS_PROMO_SK as WS_PROMO_SK -- NUMBER
, WS_BILL_HDEMO_SK as WS_BILL_HDEMO_SK -- NUMBER
, WS_EXT_SALES_PRICE as WS_EXT_SALES_PRICE -- NUMBER
, WS_SOLD_TIME_SK as WS_SOLD_TIME_SK -- NUMBER
, WS_SHIP_HDEMO_SK as WS_SHIP_HDEMO_SK -- NUMBER
, WS_ORDER_NUMBER as WS_ORDER_NUMBER -- NUMBER
, WS_BILL_CUSTOMER_SK as WS_BILL_CUSTOMER_SK -- NUMBER
, WS_WEB_PAGE_SK as WS_WEB_PAGE_SK -- NUMBER
, WS_WAREHOUSE_SK as WS_WAREHOUSE_SK -- NUMBER
, WS_SHIP_DATE_SK as WS_SHIP_DATE_SK -- NUMBER
, WS_SOLD_DATE_SK as WS_SOLD_DATE_SK -- NUMBER

from source
)

select * from transformed

