with source as (

select * from {{ source('sources', 'catalog_sales') }}

)
,

transformed as (

select 

  CS_SHIP_ADDR_SK as CS_SHIP_ADDR_SK -- NUMBER
, CS_BILL_ADDR_SK as CS_BILL_ADDR_SK -- NUMBER
, CS_EXT_WHOLESALE_COST as CS_EXT_WHOLESALE_COST -- NUMBER
, CS_SOLD_DATE_SK as CS_SOLD_DATE_SK -- NUMBER
, CS_NET_PAID as CS_NET_PAID -- NUMBER
, CS_CALL_CENTER_SK as CS_CALL_CENTER_SK -- NUMBER
, CS_SHIP_HDEMO_SK as CS_SHIP_HDEMO_SK -- NUMBER
, CS_COUPON_AMT as CS_COUPON_AMT -- NUMBER
, CS_NET_PROFIT as CS_NET_PROFIT -- NUMBER
, CS_ORDER_NUMBER as CS_ORDER_NUMBER -- NUMBER
, CS_NET_PAID_INC_SHIP_TAX as CS_NET_PAID_INC_SHIP_TAX -- NUMBER
, CS_QUANTITY as CS_QUANTITY -- NUMBER
, CS_PROMO_SK as CS_PROMO_SK -- NUMBER
, CS_EXT_LIST_PRICE as CS_EXT_LIST_PRICE -- NUMBER
, CS_EXT_SALES_PRICE as CS_EXT_SALES_PRICE -- NUMBER
, CS_NET_PAID_INC_SHIP as CS_NET_PAID_INC_SHIP -- NUMBER
, CS_CATALOG_PAGE_SK as CS_CATALOG_PAGE_SK -- NUMBER
, CS_NET_PAID_INC_TAX as CS_NET_PAID_INC_TAX -- NUMBER
, CS_EXT_SHIP_COST as CS_EXT_SHIP_COST -- NUMBER
, CS_SHIP_DATE_SK as CS_SHIP_DATE_SK -- NUMBER
, CS_SOLD_TIME_SK as CS_SOLD_TIME_SK -- NUMBER
, CS_ITEM_SK as CS_ITEM_SK -- NUMBER
, CS_BILL_CUSTOMER_SK as CS_BILL_CUSTOMER_SK -- NUMBER
, CS_EXT_TAX as CS_EXT_TAX -- NUMBER
, CS_BILL_CDEMO_SK as CS_BILL_CDEMO_SK -- NUMBER
, CS_LIST_PRICE as CS_LIST_PRICE -- NUMBER
, CS_WAREHOUSE_SK as CS_WAREHOUSE_SK -- NUMBER
, CS_EXT_DISCOUNT_AMT as CS_EXT_DISCOUNT_AMT -- NUMBER
, CS_BILL_HDEMO_SK as CS_BILL_HDEMO_SK -- NUMBER
, CS_SHIP_CUSTOMER_SK as CS_SHIP_CUSTOMER_SK -- NUMBER
, CS_WHOLESALE_COST as CS_WHOLESALE_COST -- NUMBER
, CS_SHIP_CDEMO_SK as CS_SHIP_CDEMO_SK -- NUMBER
, CS_SALES_PRICE as CS_SALES_PRICE -- NUMBER
, CS_SHIP_MODE_SK as CS_SHIP_MODE_SK -- NUMBER

from source

)

select * from transformed