
with source as (

select * from {{ source('sources', 'store_sales') }}

)
,

transformed as (
    
select 
    
 SS_SOLD_TIME_SK as SS_SOLD_TIME_SK -- NUMBER
, SS_PROMO_SK as SS_PROMO_SK -- NUMBER
, SS_QUANTITY as SS_QUANTITY -- NUMBER
, SS_EXT_DISCOUNT_AMT as SS_EXT_DISCOUNT_AMT -- NUMBER
, SS_CDEMO_SK as SS_CDEMO_SK -- NUMBER
, SS_TICKET_NUMBER as SS_TICKET_NUMBER -- NUMBER
, SS_ITEM_SK as SS_ITEM_SK -- NUMBER
, SS_ADDR_SK as SS_ADDR_SK -- NUMBER
, SS_COUPON_AMT as SS_COUPON_AMT -- NUMBER
, SS_NET_PROFIT as SS_NET_PROFIT -- NUMBER
, SS_EXT_TAX as SS_EXT_TAX -- NUMBER
, SS_NET_PAID_INC_TAX as SS_NET_PAID_INC_TAX -- NUMBER
, SS_LIST_PRICE as SS_LIST_PRICE -- NUMBER
, SS_EXT_WHOLESALE_COST as SS_EXT_WHOLESALE_COST -- NUMBER
, SS_SOLD_DATE_SK as SS_SOLD_DATE_SK -- NUMBER
, SS_HDEMO_SK as SS_HDEMO_SK -- NUMBER
, SS_STORE_SK as SS_STORE_SK -- NUMBER
, SS_CUSTOMER_SK as SS_CUSTOMER_SK -- NUMBER
, SS_NET_PAID as SS_NET_PAID -- NUMBER
, SS_EXT_LIST_PRICE as SS_EXT_LIST_PRICE -- NUMBER
, SS_WHOLESALE_COST as SS_WHOLESALE_COST -- NUMBER
, SS_SALES_PRICE as SS_SALES_PRICE -- NUMBER
, SS_EXT_SALES_PRICE as SS_EXT_SALES_PRICE -- NUMBER

from source
)

select * from transformed